---
knit: "bookdown::preview_chapter"
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}
library(meetupr)
library(tidyverse)
library(kableExtra)
library(lubridate)

meetup_johannesburg <- data.frame(get_events("Joburg-R-Users-Group",event_status = c("past", "upcoming")))
meetup_rladies_johannesburg <- data.frame(get_events("rladies-johannesburg",event_status = c("past", "upcoming")))
meetup_rladies_cape_town <- data.frame(get_events("rladies-cape-town",event_status = c("past", "upcoming")))
```

# Our R Events

## Past and Upcoming Events

#### Johannesburg R User Group

```{r, echo = FALSE}
meetup_johannesburg %>% 
  filter(time >= today() %m+% months(-6) & time <= today() %m+% months(6) ) %>%
  #add_column(event_type = "Johannesburg R User Group" ) %>%
  mutate(name = cell_spec(name, "html", link = link)) %>% 
  select(name, time, venue_name) %>%
  arrange(desc(time)) %>% 
  kable("html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

#### R-Ladies Johannesburg
```{r, echo = FALSE}
meetup_rladies_johannesburg %>% 
  filter(time >= today() %m+% months(-6) & time <= today() %m+% months(6) ) %>% 
  #add_column(event_type = "R-Ladies Johannesburg" ) %>%
  mutate(name = cell_spec(name, "html", link = link)) %>% 
  select(name, time, venue_name) %>% 
  arrange(desc(time)) %>% 
  kable("html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

#### R-Ladies Cape Town
```{r, echo = FALSE}
meetup_rladies_cape_town %>% 
  filter(time >= today() %m+% months(-6) & time <= today() %m+% months(6) ) %>% 
  #add_column(event_type = "R-Ladies Cape Town" ) %>% 
  mutate(name = cell_spec(name, "html", link = link)) %>% 
  select(name, time, venue_name) %>% 
  arrange(desc(time)) %>% 
  kable("html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

## Gallery
