---
knit: "bookdown::preview_chapter"
---

# R Community Events

The format for listing an R event is

  * Date: [event name & link](http://www.example.com). Town, Country. [Recordings here & link](http://www.example.com) [Slides here & link](http://www.example.com)

More events can be found at the [RStudio Community website](https://community.rstudio.com/c/irl)

## 2018 {-}

### May
  * May 31-Jun 6: [Data Science Africa 2018](http://www.datascienceafrica.org/dsa2018/). Nyeri, Kenya.

### June

 *  June 1-2: [R/Finance 2018](http://www.rinfinance.com). Chicago, USA.
 *  June 2: [CascadiaRConf](https://www.cascadiarconf.com). Portland, USA.

### July

 * July 2-5: [WhyR? 2018](http://whyr2018.pl/). Wroclaw, Poland.
 * July 4-6: [7eme rencontres R](https://r2018-rennes.sciencesconf.org). Rennes, France.
 * July 9-13: [R Software Fundamentals with Applications to Statistical Analyses and Modelling](http://www.sastat.org.za/sites/default/files/inline-files/2018-04-08_ShortCourse-RSoftwareFundamentals_Version-Noticeboards%28WithURL%29.pdf). Johannesburg, South Africa.
 * July 10-13: [useR! 2018](https://user2018.r-project.org/). Brisbane, Australia.
 * July: [Noreast'R Conference](http://noreastrconf.com/). Providence, USA.

### September

 * September 4-5: [LatinR 2018](http://latin-r.com/). Buenos Aires, Argentina.
 * September 11-13: [EARL London 2018](https://earlconf.com/london/). London, United Kingdom.
 * September 12-14: [The Use of R in Official Statistics](https://www.aanmelder.nl/uros2018). Hague, Netherlands.
 
### November

 * November 7: [EARL Seattle](https://earlconf.com/boston). Seattle, USA.
 * November 9: [EARL Houston](https://earlconf.com/boston). Houston, USA.
 * November 13: [EARL Boston](https://earlconf.com/boston). Boston, USA.
 * November 12-14: [Data Science Africa 2018 Abuja](http://www.datascienceafrica.org/dsa2018abuja/). Abuja, Nigeria.

## 2019 {-}

### January

  * January 15-18: [rstudio::conf](https://www.rstudio.com/conference/). Austin, USA.

### July

  * July 9-12: [useR! 2019](http://www.user2019.fr/). Toulouse, France.

## Past R Community Events Resources

### Archive - 2018 {-}

  * January 31, Feb 1-3: [rstudio::conf](https://www.rstudio.com/conference/). San Diego, USA. ([Recordings here](https://www.rstudio.com/resources/webinars/#cd2efd7cff89930bc))
  * March 17th: [SatRday](http://capetown2018.satrdays.org/). Cape Town, South Africa. ([Recordings here](https://www.youtube.com/watch?v=bVweO74kvtc&list=PLQPtslMzGu4oDr6hjKm1aQ2XN7P35vCbk))
  * May: [The European #rstats Users Meeting](http://2018.erum.io/). Budapest, Hungary.  ([Recordings here](https://www.youtube.com/watch?list=PLUBl0DoLa5SAo_XRnkQA5GtEORg9K7kMh&v=4XxOUPgs9tc))

### Archive - 2017 {-}

 * January 11-14: [rstudio::conf](https://www.rstudio.com/conference/). Kissmmee, USA. ([Recordings here](https://www.rstudio.com/resources/webinars/#ed21d83e49156bae4))
  * February 16-18: [satRday](http://satrdays.org/capetown2017/). Cape Town, South Africa. ([Recordings here]())
  * April 21-22: [New York R Conference 2017](http://www.rstats.nyc). New York, USA. ([Recordings here](https://www.rstats.nyc/2017/))
  * May 19-20: [R/Finance 2017](http://www.rinfinance.com). Chicago, USA. ([Recordings here](https://channel9.msdn.com/Events/RFinance/RFinance-2017))
  * July 4-7: [UseR! 2017](http://www.user2017.brussels/). Brussels, Belgium. [Recordings](https://channel9.msdn.com/events/useR-international-R-User-conferences/)

### Archive - 2016 {-}

  * April: [New York R Conference 2016](http://www.rstats.nyc). New York, USA. ([Recordings here](https://www.rstats.nyc/2017/))
  * July: [UseR! 2016](http://user2016.org/). Stanford, USA. ([Recordings here](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016))
