---
title: "Our R Events"
editor: visual
---

```{r load-token, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}
key <- cyphr::key_sodium(sodium::hex2bin(Sys.getenv("MEETUPR_PWD")))

temptoken <- tempfile(fileext = ".rds")

cyphr::decrypt_file(
  "secret.rds",
  key = key,
  dest = temptoken
)

meetupr::meetup_auth(
  verbose = meetupr_verbose(),
  token = temptoken
)
```

## Upcoming Events

### Johannesburg R User Group

```{r, echo = FALSE}
urlname <- "Joburg-R-Users-Group"
jhbr_events <- meetupr::get_events(urlname) |>
  dplyr::distinct() |> # method is returning duplicates
  dplyr::arrange(desc(time))

jhbr_events |>
  dplyr::filter(status %in% c("published")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Johannesburg

```{r, echo = FALSE}
urlname <- "rladies-johannesburg"
rladiesjhb_events <- meetupr::get_events(urlname) |>
  dplyr::distinct() |> # method is returning duplicates
  dplyr::arrange(desc(time))

rladiesjhb_events |>
  dplyr::filter(status %in% c("published")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Cape Town

```{r, echo = FALSE}
urlname <- "rladies-cape-town"
rladiescpt_events <- meetupr::get_events(urlname) |>
  dplyr::distinct() |> # method is returning duplicates
  dplyr::arrange(desc(time))

rladiescpt_events |>
  dplyr::filter(status %in% c("published")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

## Past Events

### Johannesburg R User Group

```{r, echo = FALSE}
jhbr_events |>
  dplyr::filter(status %in% c("PAST")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Johannesburg

```{r, echo = FALSE}
rladiesjhb_events |>
  dplyr::filter(status %in% c("PAST")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Cape Town

```{r, echo = FALSE}
rladiescpt_events |>
  dplyr::filter(status %in% c("PAST")) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link),
                date = lubridate::ymd_hms(format(time, "%Y-%m-%d 00:00:00"))) |>
  dplyr::select("Date" = date, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```
