---
title: "Our R Events"
editor: visual
---

```{r generate-token, include = FALSE}
ttt <- meetupr::meetup_auth(
  cache = TRUE,
  use_appdir = FALSE
)
#sodium_key <- sodium::keygen()
#save an env variable Sys.setenv("MEETUPR_PWD" = sodium::bin2hex(sodium_key))
key <- cyphr::key_sodium(sodium::hex2bin(Sys.getenv("MEETUPR_PWD")))
cyphr::encrypt_file(
  ".httr-oauth",
  key = key,
  dest = "secret.rds"
)
```

```{r load-token, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}

key <- cyphr::key_sodium(sodium::hex2bin(Sys.getenv("MEETUPR_PWD")))

temptoken <- tempfile(fileext = ".rds")

cyphr::decrypt_file(
  "secret.rds",
  key = key,
  dest = temptoken
)

meetupr::meetup_auth(
  verbose = meetupr_verbose(),
  token = temptoken
)
```

## Past and Upcoming Events

### Johannesburg R User Group

```{r, echo = FALSE}
urlname <- "Joburg-R-Users-Group"
events <- meetupr::get_events(urlname)
dplyr::arrange(events, desc(time)) |>
  dplyr::filter(status %in% c("PAST", "published")) |>
  dplyr::top_n(5,time) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link)) |>
  dplyr::select("Time" = time, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Johannesburg

```{r, echo = FALSE}
urlname <- "rladies-johannesburg"
events <- meetupr::get_events(urlname)
dplyr::arrange(events, desc(time)) |>
  dplyr::filter(status %in% c("PAST", "published")) |>
  dplyr::top_n(5,time) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link)) |>
  dplyr::select("Time" = time, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### R-Ladies Cape Town

```{r, echo = FALSE}
urlname <- "rladies-cape-town"
events <- meetupr::get_events(urlname)
dplyr::arrange(events, desc(time)) |>
  dplyr::filter(status %in% c("PAST", "published")) |>
  dplyr::top_n(5,time) |>
  dplyr::mutate(title = kableExtra::cell_spec(title, "html", link = link)) |>
  dplyr::select("Time" = time, "Title" = title, "Venue" = venue_name) |>
  kableExtra::kable("html", escape = FALSE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```
